### ISSUE TITLE
`mergeOpenApiFiles` task gives different results on different OS

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspacecomponents/DataSpaceConnector#1415]
# Bug Report

## Describe the Bug
Since a modification to an api is made, the openapi files must be recreated to make the `OpenAPI-Definitions` check pass.
Seems like the files recreated on a Window 11 (in this case by @tuncaytunc-zf )  machines are different from the ones created by the CI

### Expected Behavior
To have the same output files on every OS.

### Observed Behavior
-

## Steps to Reproduce
-

## Context Information
Not sure about the `bug` label since that's not an issue on our side, but could a problem for non-NIX contibutors

## Detailed Description
-

## Possible Implementation
-

**Comment by paullatzelsperger** [comment]
Keep in mind, two subsequent calls to `mergeOpenApiFiles` can _always_ yield different results, because the ordering inside the yaml will change. 
That's why the CI check step does some sort of ordering first.

Just because I saw this on @tuncaytunc-zf's PR: removing an `@NotNull` annotation _will_ change the generated yaml!

**Comment by ndr-brt** [comment]
@paullatzelsperger we found out this issue in that PR, since the `openapi.yaml` generated by @tuncaytunc-zf was breaking the CI job, while the one generated by me is actually working.

This could depend by https://github.com/kpramesh2212/openapi-merger-plugin/pull/11, let's see after merge and release of it if the issue still exist

(ps. we were aware of the `@Null` removal, as it was breaking some tests.)

**Comment by paullatzelsperger** [comment]
Have you tried actually _deleting_ and recreating all of your local yaml files? Had some weird effects with this once

**Comment by ndr-brt** [comment]
From my machine (linux) on the #1407 branch, deleting everything and recreating again makes the new `openapi.yaml` differs from the committed one (that's passing the CI check), but I guess that the current check sorts the yaml before the actual check.

@tuncaytunc-zf could you try to delete the `resources/openapi` folder, recreate the definitions and push them? If they breaks I think we have a problem (and the latest commit can be reverted), otherwise let's close this.

**Comment by paullatzelsperger** [comment]
I've had that error too, but it turned out to be a user error on my part :)
Generally, it indicates that a `@NonNull` property was either added or removed, but the yaml was not regenerated properly. 
The check takes the checked-in openapi.yaml, regenerates it and compares those two versions (canonically). 

I suspect the problem could be that there are two DTOs (here: `ContractDefinitionDto`) with the same name, but with different properties (or validation constraints), so the merger overwrites one with the other, and whichever comes first will be used for comparison.

**Comment by tuncaytunc-zf** [comment]
I have regenerated all files again without any Dto changes and there were no semantic difference in the new generated files. Don't know what went wrong the last times. @paullatzelsperger which OS are you using?

**Comment by paullatzelsperger** [comment]
I suspect it's less about DTO _changes_, than rather about the fact that there are two classes with the same class name (See comment above).
So whether or not an error is thrown is somewhat random, as it depends on which one of those is read first.

I also it does not depend on the OS, I'm running linux, and so is the Github actions runner.
